# Specify we are working with a Java project.
# Travis can be used also for many other languages.
language: java

# The JDK we need for compiling
jdk:
  - oraclejdk8

# As the build will download JAR files from Maven Central, optimize their storage,
# so they do not get re-downloaded each time
cache:
  directories:
  - .autoconf
  - $HOME/.m2

# Useful when working in team. If someone breaks the build (code does not compile
# or some tests are failing), then get notified by email immediately.
notifications:
email: true

# The actual command we do for compiling.
# Note: Travis has a quite limited handling of build log files, so need
# to minimize them, ie do not be too verbose
script: mvn clean verify  --quiet